import './globals.css'
import styles from "./layout.module.scss"
import Menu from "@/components/menu/Menu/Menu";
import MenuContent from "@/components/menu/MenuContent/MenuContent";
import ListsTagsContextLoad from "@/store/ListsTagsContextLoad";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <ListsTagsContextLoad>
          <Menu>
            <MenuContent/>
          </Menu>
          {children}
        </ListsTagsContextLoad>
      </body>
    </html>
  )
}
