import './globals.css'
import styles from "./layout.module.scss"
import Menu from "@/components/menu/Menu/Menu";
import TasksContextProvider from "@/store/TasksContext";
import {requestGetLists} from "@/requests/ListRequests";
import {requestGetTags} from "@/requests/TagRequests";
import ListsContextProvider from "@/store/ListsContext";
import TagsContextProvider from "@/store/TagsContext";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const lists = await requestGetLists();
  const tags = await requestGetTags();

  return (
    <html lang="en">
      <body className={styles.body}>
        <ListsContextProvider initial={lists}>
          <TagsContextProvider initial={tags}>
            <TasksContextProvider>
              <Menu/>
              {children}
            </TasksContextProvider>
          </TagsContextProvider>
        </ListsContextProvider>
      </body>
    </html>
  )
}
